### ISSUE TITLE
Seitenumbrüche

### ISSUE THREAD

**Issue by ottosmops** [bullinger-digital/bullinger-tei#6]
Beispiel https://www.bullinger-digital.ch/letter/236

Der Seitenumbruch ist nicht im XML markiert.

Idealerweise müsste `<pb facs="236/Autograph/00 E_II_351__fol__79_r_.tif" />` am Beginn des Textes und `<pb facs="236/Autograph/00 E_II_351__fol__79_v_.tif" />` an der richtigen Stelle im Text plaziert sein. Das gilt auch für den Nachtrag. vgl. auch unser review vom Dez. 2022.

**Comment by ottosmops** [comment]
Alternativ:

- Alle facsimile/graphic bekommen eine xml:id (z.B. filename ohne Endung)
- `<pb>` bekommt ein `@facs` das ebendiese ID enthält

**Comment by tuurma** [comment]
Please see #8 for full requirements list regarding referencing images. NB: please no spaces in file names.
